CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS agencies (
  id TEXT PRIMARY KEY,
  feed_id TEXT NOT NULL,
  name TEXT NOT NULL,
  url TEXT,
  timezone TEXT,
  lang TEXT
);

CREATE TABLE IF NOT EXISTS routes (
  id TEXT PRIMARY KEY,
  agency_id TEXT NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,
  feed_route_id TEXT NOT NULL,
  short_name TEXT,
  long_name TEXT,
  route_type INTEGER NOT NULL,
  color TEXT,
  text_color TEXT,
  UNIQUE (agency_id, feed_route_id)
);

CREATE TABLE IF NOT EXISTS stops (
  id TEXT PRIMARY KEY,
  agency_id TEXT NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,
  feed_stop_id TEXT NOT NULL,
  name TEXT NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  location geography(Point, 4326) NOT NULL,
  UNIQUE (agency_id, feed_stop_id)
);

CREATE TABLE IF NOT EXISTS shape_catalog (
  id TEXT PRIMARY KEY,
  agency_id TEXT NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,
  feed_shape_id TEXT NOT NULL,
  UNIQUE (agency_id, feed_shape_id)
);

CREATE TABLE IF NOT EXISTS shapes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shape_id TEXT NOT NULL REFERENCES shape_catalog(id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  location geography(Point, 4326) NOT NULL,
  UNIQUE (shape_id, sequence)
);

CREATE TABLE IF NOT EXISTS trips (
  id TEXT PRIMARY KEY,
  feed_trip_id TEXT NOT NULL,
  route_id TEXT NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
  service_id TEXT NOT NULL,
  shape_id TEXT REFERENCES shape_catalog(id) ON DELETE SET NULL,
  direction_id TEXT,
  headsign TEXT,
  UNIQUE (route_id, feed_trip_id)
);

CREATE TABLE IF NOT EXISTS stop_times (
  trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  stop_id TEXT NOT NULL REFERENCES stops(id) ON DELETE CASCADE,
  arrival_time TEXT,
  departure_time TEXT,
  stop_sequence INTEGER NOT NULL,
  PRIMARY KEY (trip_id, stop_sequence)
);

CREATE TABLE IF NOT EXISTS route_shapes (
  route_id TEXT NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
  shape_id TEXT NOT NULL REFERENCES shape_catalog(id) ON DELETE CASCADE,
  geometry geometry(LineString, 4326) NOT NULL,
  PRIMARY KEY (route_id, shape_id)
);

CREATE TABLE IF NOT EXISTS route_shape_variants (
  route_id TEXT NOT NULL,
  shape_id TEXT NOT NULL,
  direction_id TEXT NOT NULL DEFAULT '',
  headsign TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (route_id, shape_id, direction_id, headsign),
  FOREIGN KEY (route_id, shape_id)
    REFERENCES route_shapes(route_id, shape_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS stops_location_gix ON stops USING GIST (location);
CREATE INDEX IF NOT EXISTS shapes_location_gix ON shapes USING GIST (location);
CREATE INDEX IF NOT EXISTS route_shapes_geometry_gix ON route_shapes USING GIST (geometry);
CREATE INDEX IF NOT EXISTS route_shapes_geography_gix ON route_shapes USING GIST ((geometry::geography));
CREATE INDEX IF NOT EXISTS routes_agency_idx ON routes (agency_id);
CREATE INDEX IF NOT EXISTS trips_route_idx ON trips (route_id);
CREATE INDEX IF NOT EXISTS trips_shape_idx ON trips (shape_id);
CREATE INDEX IF NOT EXISTS stop_times_stop_idx ON stop_times (stop_id);